// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NewCafeAuto.Models
{
    public partial class Addresses
    {
        public int Id { get; set; }
        public string Street { get; set; }
        public string Town { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string FullAddress { get; set; }
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
        public int? UserId { get; set; }
        public int? CompanyId { get; set; }
        public int? CafeId { get; set; }

        public virtual Cafe Cafe { get; set; }
        public virtual Company Company { get; set; }
        public virtual Users User { get; set; }
    }
}