// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NewCafeAuto.Models
{
    public partial class Cafe
    {
        public Cafe()
        {
            Addresses = new HashSet<Addresses>();
            Menu = new HashSet<Menu>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public int? CompanyId { get; set; }
        public int? MenuId { get; set; }

        public virtual Company Company { get; set; }
        public virtual ICollection<Addresses> Addresses { get; set; }
        public virtual ICollection<Menu> Menu { get; set; }
    }
}