// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NewCafeAuto.Models
{
    public partial class Company
    {
        public Company()
        {
            Addresses = new HashSet<Addresses>();
            Cafe = new HashSet<Cafe>();
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string Photo { get; set; }
        public string Registration { get; set; }
        public string PasswordResetToken { get; set; }
        public DateTime? PasswordResetTokenExpiresAt { get; set; }
        public string EmailProofToken { get; set; }
        public DateTime? EmailProofTokenExpiresAt { get; set; }
        public string SignToken { get; set; }
        public bool? IsLogin { get; set; }

        public virtual ICollection<Addresses> Addresses { get; set; }
        public virtual ICollection<Cafe> Cafe { get; set; }
    }
}