// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NewCafeAuto.Models
{
    public partial class Menu
    {
        public Menu()
        {
            Category = new HashSet<Category>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool? IsAvailable { get; set; }
        public string CreatedDate { get; set; }
        public string UpdatedDate { get; set; }
        public int? CafeId { get; set; }

        public virtual Cafe Cafe { get; set; }
        public virtual ICollection<Category> Category { get; set; }
    }
}