// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NewCafeAuto.Models
{
    public partial class Profiles
    {
        public Profiles()
        {
            Users = new HashSet<Users>();
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string BirthDate { get; set; }
        public string PhoneNumber { get; set; }

        public virtual ICollection<Users> Users { get; set; }
    }
}