// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NewCafeAuto.Models
{
    public partial class Users
    {
        public Users()
        {
            Addresses = new HashSet<Addresses>();
            Cards = new HashSet<Cards>();
        }

        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string RegistrationDate { get; set; }
        public string PasswordResetToken { get; set; }
        public DateTime? PasswordResetTokenExpiresAt { get; set; }
        public string EmailProofToken { get; set; }
        public DateTime? EmailProofTokenExpiresAt { get; set; }
        public string SignToken { get; set; }
        public bool? IsLogin { get; set; }
        public int? ProfileId { get; set; }

        public virtual Profiles Profile { get; set; }
        public virtual ICollection<Addresses> Addresses { get; set; }
        public virtual ICollection<Cards> Cards { get; set; }
    }
}